/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guithubex;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    List<Integer> arregloNumeros = new ArrayList<>();
    public GUI() {
        initComponents();
        tamañoVector.setTransferHandler(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tamañoVector = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        Button = new javax.swing.JButton();
        sumaL = new javax.swing.JLabel();
        mediaL = new javax.swing.JLabel();
        modaL = new javax.swing.JLabel();
        medianaL = new javax.swing.JLabel();
        desvResMediaL = new javax.swing.JLabel();
        desvMediaL = new javax.swing.JLabel();
        varianzaL = new javax.swing.JLabel();
        desvEstandarL = new javax.swing.JLabel();
        media = new javax.swing.JLabel();
        moda = new javax.swing.JLabel();
        mediana = new javax.swing.JLabel();
        desvResMedia = new javax.swing.JLabel();
        desvMedia = new javax.swing.JLabel();
        varianza = new javax.swing.JLabel();
        desvEstandar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese el tamaño del vector");

        tamañoVector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tamañoVectorKeyPressed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posición", "Elemento"
            }
        ));
        table.setEnabled(false);
        jScrollPane1.setViewportView(table);

        Button.setText("Generar");
        Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMouseClicked(evt);
            }
        });

        mediaL.setText("La media de los números es:");

        modaL.setText("La moda de los números es:");

        medianaL.setText("La mediana de los números es:");

        desvResMediaL.setText("La desviación respecto de la media de los números es:");

        desvMediaL.setText("La desviación media de los números es:");

        varianzaL.setText("La varianza de los números es:");

        desvEstandarL.setText("La desviación estándar de los números es:");

        media.setText("0");

        moda.setText("jLabel2");

        mediana.setText("jLabel3");

        desvResMedia.setText("jLabel4");

        desvMedia.setText("jLabel5");

        varianza.setText("jLabel6");

        desvEstandar.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                                .addComponent(Button)))
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tamañoVector, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(135, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modaL)
                                .addGap(18, 18, 18)
                                .addComponent(moda))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mediaL)
                                .addGap(18, 18, 18)
                                .addComponent(media))
                            .addComponent(sumaL)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(medianaL)
                                .addGap(18, 18, 18)
                                .addComponent(mediana))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(desvResMediaL)
                                .addGap(18, 18, 18)
                                .addComponent(desvResMedia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(desvMediaL)
                                .addGap(18, 18, 18)
                                .addComponent(desvMedia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(varianzaL)
                                .addGap(18, 18, 18)
                                .addComponent(varianza))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(desvEstandarL)
                                .addGap(18, 18, 18)
                                .addComponent(desvEstandar)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tamañoVector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sumaL)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediaL)
                    .addComponent(media))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modaL)
                    .addComponent(moda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medianaL)
                    .addComponent(mediana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desvResMediaL)
                    .addComponent(desvResMedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desvMediaL)
                    .addComponent(desvMedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varianzaL)
                    .addComponent(varianza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desvEstandarL)
                    .addComponent(desvEstandar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMouseClicked
        if (tamañoVector.getText()==""){
            JOptionPane.showMessageDialog(null, "Señor usuario, por favor ingrese un número");
        }
        else{
            int numeroUsuario = Integer.parseInt(tamañoVector.getText());
            Random random = new Random();
            for (int i = 0; i < numeroUsuario; i++) {
                int numeroAleatorio = random.nextInt(50);
                int posicion=i+1;
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.addRow(new Object[]{posicion, numeroAleatorio});
                arregloNumeros.add(numeroAleatorio);
            }
            sumaL.setText("La suma de los elementos es "+String.valueOf(sumaPosiciones()));
            this.media.setText(String.valueOf(media()));
            moda();
            mediana();
        }
        
    }//GEN-LAST:event_ButtonMouseClicked

    private int sumaPosiciones(){
        int sumaNumeros = 0;
        for (int i = 0; i < arregloNumeros.size(); i++) {
            sumaNumeros = sumaNumeros + arregloNumeros.get(i);
        }
        return sumaNumeros;
    }
    
    private float media(){
        float media;
        int totalNumeros = arregloNumeros.size();
        int sumaTotal=0;
        for (int i = 0; i < totalNumeros; i++) {
            sumaTotal=sumaTotal+arregloNumeros.get(i);
        }
        media = sumaTotal/totalNumeros;
        return media;
    }
    
    private void moda(){
        int modaN=0;
        int numVeces=0;
        for (int i = 0; i < arregloNumeros.size(); i++) {
            if(numVeces<contadorAp(arregloNumeros.get(i))){
                modaN=arregloNumeros.get(i);
                numVeces=contadorAp(arregloNumeros.get(i));
            }
        }
        this.moda.setText(String.valueOf(modaN));
    }
    
    public int contadorAp(int num){
        int apariciones=0;
        for (int i = 0; i < arregloNumeros.size(); i++) {
            if(num==arregloNumeros.get(i)){
                apariciones++;
            }
        }
        return(apariciones);
    }
    
    private void mediana(){
        arregloNumeros.sort(null);
        float mediana=0;
        int totalNumeros=arregloNumeros.size();
        if(totalNumeros%2==0){
            int num1=arregloNumeros.get(totalNumeros/2-1);
            int num2=arregloNumeros.get(totalNumeros/2);
            mediana=(num1+num2)/2;
        }
        else{
            mediana=arregloNumeros.get(totalNumeros/2);
        }
        this.mediana.setText(String.valueOf(mediana));
    }
    
    private void desviacionEstandar(){
        float desvEstandar=0;
        float valorMedia = media();
        int totalNum = arregloNumeros.size();
        float sumatoria=0;
        for (int i = 0; i < totalNum; i++) {
            sumatoria = (float)(sumatoria+Math.pow((arregloNumeros.get(i)-valorMedia), 2));
        }
        desvEstandar = (float) Math.sqrt(sumatoria/totalNum);
        this.desvEstandar.setText(String.valueOf(desvEstandar));
    }
    
    private void tamañoVectorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tamañoVectorKeyPressed
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_tamañoVectorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JLabel desvEstandar;
    private javax.swing.JLabel desvEstandarL;
    private javax.swing.JLabel desvMedia;
    private javax.swing.JLabel desvMediaL;
    private javax.swing.JLabel desvResMedia;
    private javax.swing.JLabel desvResMediaL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel media;
    private javax.swing.JLabel mediaL;
    private javax.swing.JLabel mediana;
    private javax.swing.JLabel medianaL;
    private javax.swing.JLabel moda;
    private javax.swing.JLabel modaL;
    private javax.swing.JLabel sumaL;
    private javax.swing.JTable table;
    private javax.swing.JTextField tamañoVector;
    private javax.swing.JLabel varianza;
    private javax.swing.JLabel varianzaL;
    // End of variables declaration//GEN-END:variables
}
